(define randnom (apply get-random 1 100))
(define (setMaxTry num) (define maxTry num))

(define (guessLower try maxTry)
   (write-line (string-append "Guess Lower Attempt : " (number->string try)))
   (outofTry try maxTry))

(define (outofTry  try maxTry)
(if (< try maxTry) 
 (guessing-game (+ try 1) maxTry) 
 (write-line "Sorry out of tries")))

(define (guessHigher try maxTry)
   (write-line (string-append "Guess Higher Attempt : " (number->string try)))
   (outofTry try maxTry))

(define (guessing-game try maxTry)
    (define input (apply read-line))
    (if (= input randnom)
        (write-line "You were correct!")
        (if (> input randnom)
	          (guessLower try maxTry)
         		(guessHigher try maxTry))))

(define (main)
    (write-line "Pick a difficulty [easy/medium/hard]: ")
    (define choice (apply read-line))
    (write-line (string-append "Difficulty chosen : " choice))
    (if (string=? choice "easy")
	(define maxTry 9)
	(if (string=? choice "medium")
	    (define maxTry 7)
		(define maxTry 5)))
    (write-line (string-append "Number of attempts : " (number->string maxTry)))    
    (write-line "Guess a number between 1 - 100: ")
    (guessing-game 2 maxTry))

(main)
